In [2]:
import pandas as pd
from pandas import DataFrame
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from dotenv import load_dotenv
import os
from sqlalchemy import create_engine

### Missing Data Insights
- __Clean Tables__: Customers, Order Items, Payments, Translations, and Sellers have 0 missing values.
- __Orders Table__: Contains missing timestamps related to order fulfillment (`order_approved_at`, `order_delivered_carrier_date`, `order_delivered_customer_date`).
- __Products Table__: Missing metadata for 610 products and dimensions for 2 products.
- __Reviews Table__: High volume of missing values in text fields (`review_comment_title`, `review_comment_message`), which is expected as comments are optional.

In [3]:
## Create Connection
load_dotenv()
password = os.getenv("PASSWORD")
conn = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/OlistCustomerDB"
)

In [4]:
customers = "SELECT * FROM staging.customers;"
df_customers = pd.read_sql(customers, con=conn)

geolocation = "SELECT * FROM staging.geolocation;"
df_geolocation = pd.read_sql(geolocation, con=conn)

order_items = "SELECT * FROM staging.order_items;"
df_order_items = pd.read_sql(order_items, con=conn)

order_payments = "SELECT * FROM staging.order_payments;"
df_order_payments = pd.read_sql(order_payments, con=conn)

order_reviews = "SELECT * FROM staging.order_reviews;"
df_order_reviews = pd.read_sql(order_reviews, con=conn)

orders = "SELECT * FROM staging.orders;"
df_orders = pd.read_sql(orders, con=conn)

products = "SELECT * FROM staging.products;"
df_products = pd.read_sql(products, con=conn)

sellers = "SELECT * FROM staging.sellers;"
df_sellers = pd.read_sql(sellers, con=conn)

In [5]:
def measures(df: DataFrame):
    print(df.head().to_markdown())
    print("\n")
    print("_"*60)
    print(df.info())
    print("\n")
    print("_"*60)
    print("Shape:\n")
    print(df.shape)
    print("\n")
    print("_"*60)
    print("Null values:")
    print(df.isnull().sum())
    print("\n")
    print("_"*60)
    print("Duplicates:")
    print(df.duplicated(keep="first").sum())

#### 1. Customers

In [6]:
measures(df_customers)

|    | customer_id                      | customer_unique_id               |   customer_zip_code_prefix | customer_city         | customer_state   |
|---:|:---------------------------------|:---------------------------------|---------------------------:|:----------------------|:-----------------|
|  0 | 06b8999e2fba1a1fbc88172c00ba8bc7 | 861eff4711a542e4b93843c6dd7febb0 |                      14409 | franca                | SP               |
|  1 | 18955e83d337fd6b2def6b18a428ac77 | 290c77bc529b7ac935b93aa66c333dc3 |                      09790 | sao bernardo do campo | SP               |
|  2 | 4e7b3e00288586ebd08712fdd0374a03 | 060e732b5b29e8181a18229c7b0b2b5e |                      01151 | sao paulo             | SP               |
|  3 | b2b6027bc5c5109e529d4dc6358b12c3 | 259dac757896d24d7702b9acbbff3f3c |                      08775 | mogi das cruzes       | SP               |
|  4 | 4f2d8ab171c80ec8364f7c12e35b23ad | 345ecd01c38d18a9036ed96c73b8d066 |                      13056 | campinas              | SP               |


____________________________________________________________
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  str
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: str(5)
memory usage: 3.8 MB
None


____________________________________________________________
Shape:

(99441, 5)


____________________________________________________________
Null values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64


____________________________________________________________
Duplicates:
0

#### 2. Geolocation
- Contains null values for 162 Zip_codes
    - These are those zip_codes which we added to geolocation from sellers and customers dataset, that were originally missing from geolocation. And inorder to define FK we added these instances to geolocation
    - Best choice would be to fill these mannually 
    - But for now leave them as Null

In [7]:
measures(df_geolocation)

|    |   zip_code |   latitude |   longitude | city      | geo_state   |
|---:|-----------:|-----------:|------------:|:----------|:------------|
|  0 |      01001 |   -23.5502 |    -46.634  | sao paulo | SP          |
|  1 |      01002 |   -23.5481 |    -46.635  | sao paulo | SP          |
|  2 |      01003 |   -23.549  |    -46.6357 | sao paulo | SP          |
|  3 |      01004 |   -23.5498 |    -46.6348 | sao paulo | SP          |
|  4 |      01005 |   -23.5495 |    -46.6367 | sao paulo | SP          |


____________________________________________________________
<class 'pandas.DataFrame'>
RangeIndex: 19177 entries, 0 to 19176
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   zip_code   19177 non-null  str
 1   latitude   19015 non-null  float64
 2   longitude  19015 non-null  float64
 3   city       19015 non-null  str
 4   geo_state  19015 non-null  str
dtypes: float64(2), str(3)
memory usage: 749.2 KB
None


____________________________________________________________
Shape:

(19177, 5)


____________________________________________________________
Null values:
zip_code       0
latitude     162
longitude    162
city         162
geo_state    162
dtype: int64


____________________________________________________________
Duplicates:
0

In [8]:
## Check null values
df_geolocation[df_geolocation.isnull().any(axis=1)]

      zip_code  latitude  longitude city geo_state
19015    02140       NaN        NaN  NaN       NaN
19016    02285       NaN        NaN  NaN       NaN
19017    06930       NaN        NaN  NaN       NaN
19018    07412       NaN        NaN  NaN       NaN
19019    07430       NaN        NaN  NaN       NaN
...        ...       ...        ...  ...       ...
19172    91901       NaN        NaN  NaN       NaN
19173    93602       NaN        NaN  NaN       NaN
19174    94370       NaN        NaN  NaN       NaN
19175    95572       NaN        NaN  NaN       NaN
19176    95853       NaN        NaN  NaN       NaN

[162 rows x 5 columns]

#### 3. Order Items

In [9]:
measures(df_order_items)

|    | order_id                         |   order_item_id | product_id                       | seller_id                        | shipping_limit_date   |   price |   freight_value |
|---:|:---------------------------------|----------------:|:---------------------------------|:---------------------------------|:----------------------|--------:|----------------:|
|  0 | 00010242fe8c5a6d1ba2dd792cb16214 |               1 | 4244733e06e7ecb4970a6e2683c13e61 | 48436dade18ac8b2bce089ec2a041202 | 2017-09-19 09:45:35   |   58.9  |           13.29 |
|  1 | 00018f77f2f0320c557190d7a144bdd3 |               1 | e5f2d52b802189ee658865ca93d83a8f | dd7ddc04e1b6c2c614352b383efe2d36 | 2017-05-03 11:05:13   |  239.9  |           19.93 |
|  2 | 000229ec398224ef6ca0657da4fc703e |               1 | c777355d18b72b67abbeef9df44fd0fd | 5b51032eddd242adc84c38acab88f23d | 2018-01-18 14:48:30   |  199    |           17.87 |
|  3 | 00024acbcdf0a6daa1e931b038114c75 |               1 | 7634da152a4610f1595efa32f14722fc | 9d7a1d34a5052409006425275ba1c2b4 | 2018-08-15 10:10:18   |   12.99 |           12.79 |
|  4 | 00042b26cf59d7ce69dfabb4e55b4fd9 |               1 | ac6c3623068f30de03045865e4e10089 | df560393f3a51e74553ab94004ba5c87 | 2017-02-13 13:57:51   |  199.9  |           18.14 |


____________________________________________________________
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  datetime64[us]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.0 MB
None


____________________________________________________________
Shape:

(112650, 7)


____________________________________________________________
Null values:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64


____________________________________________________________
Duplicates:
0

#### 4. Order Payments

In [10]:
measures(df_order_payments)

|    | order_id                         |   payment_sequential | payment_type   |   payment_installments |   payment_value |
|---:|:---------------------------------|---------------------:|:---------------|-----------------------:|----------------:|
|  0 | b81ef226f3fe1789b1e8b2acac839d17 |                    1 | credit_card    |                      8 |           99.33 |
|  1 | a9810da82917af2d9aefd1278f1dcfa0 |                    1 | credit_card    |                      1 |           24.39 |
|  2 | 25e8ea4e93396b6fa0d3dd708e76c1bd |                    1 | credit_card    |                      1 |           65.71 |
|  3 | ba78997921bbcdc1373bb41e913ab953 |                    1 | credit_card    |                      8 |          107.78 |
|  4 | 42fdf880ba16b47b59251dd489d4441a |                    1 | credit_card    |                      2 |          128.45 |


____________________________________________________________
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB
None


____________________________________________________________
Shape:

(103886, 5)


____________________________________________________________
Null values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64


____________________________________________________________
Duplicates:
0

#### 5. Order Reviews
- `review_comment_title` and `review_comment_message` have lots of missing data - that makes sense because people usually just give star rating (1-5) without any descriptive review

In [11]:
measures(df_order_reviews)

|    | review_id                        | order_id                         |   review_score |   review_comment_title | review_comment_message                                                                               | review_creation_date   | review_answer_timestamp   |
|---:|:---------------------------------|:---------------------------------|---------------:|-----------------------:|:-----------------------------------------------------------------------------------------------------|:-----------------------|:--------------------------|
|  0 | 7bc2406110b926393aa56f80a40eba40 | 73fc7af87114b39712e6da79b0a377eb |              4 |                    nan | nan                                                                                                  | 2018-01-18             | 2018-01-18 21:46:59       |
|  1 | 80e641a11e56f04c1ad469d5645fdfde | a548910a1c6147796b98fdf73dbeba33 |              5 |                    nan | nan                                                                                                  | 2018-03-10             | 2018-03-11 03:05:13       |
|  2 | 228ce5500dc1d8e020d8d1322874b6f0 | f9e4b658b201a9f2ecdecbb34bed034b |              5 |                    nan | nan                                                                                                  | 2018-02-17             | 2018-02-18 14:36:24       |
|  3 | e64fb393e7b32834bb789ff8bb30750e | 658677c97b385a9be170737859d3511b |              5 |                    nan | Recebi bem antes do prazo estipulado.                                                                | 2017-04-21             | 2017-04-21 22:02:06       |
|  4 | f7c4243c7fe1938f181bec41a392bdeb | 8e6bfb81e283fa7e4f11123a3fb894f1 |              5 |                    nan | Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Páscoa | 2018-03-01             | 2018-03-02 10:26:53       |


____________________________________________________________
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(1), object(1), str(4)
memory usage: 5.3+ MB
None


____________________________________________________________
Shape:

(99224, 7)


____________________________________________________________
Null values:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64


____________________________________________________________
Duplicates:
0

#### 6. Orders
- Missing data in -   
 `order_approved_at`,   
 `order_delivered_carrier_date`,   
 `order_delivered_customer_date`
- Analyse `order_status` to understand why these missing values exist

- Conclusion -   
The missing data here is mainly because some orders are - cancelled, in processing, or unavailable etc     
And only few instances are genuine error 

- Decision: Keep all missing data as null

In [12]:
measures(df_orders)

|    | order_id                         | customer_id                      | order_status   | order_purchase_timestamp   | order_approved_at   | order_delivered_carrier_date   | order_delivered_customer_date   | order_estimated_delivery_date   |
|---:|:---------------------------------|:---------------------------------|:---------------|:---------------------------|:--------------------|:-------------------------------|:--------------------------------|:--------------------------------|
|  0 | e481f51cbdc54678b7cc49136f2d6af7 | 9ef432eb6251297304e76186b10a928d | delivered      | 2017-10-02 10:56:33        | 2017-10-02 11:07:15 | 2017-10-04 19:55:00            | 2017-10-10 21:25:13             | 2017-10-18                      |
|  1 | 53cdb2fc8bc7dce0b6741e2150273451 | b0830fb4747a6c6d20dea0b8c802d7ef | delivered      | 2018-07-24 20:41:37        | 2018-07-26 03:24:27 | 2018-07-26 14:31:00            | 2018-08-07 15:27:45             | 2018-08-13                      |
|  2 | 47770eb9100c2d0c44946d9cf07ec65d | 41ce2a54c0b03bf3443c3d931a367089 | delivered      | 2018-08-08 08:38:49        | 2018-08-08 08:55:23 | 2018-08-08 13:50:00            | 2018-08-17 18:06:29             | 2018-09-04                      |
|  3 | 949d5b44dbf5de918fe9c16f97b45f8a | f88197465ea7920adcdbec7375364d82 | delivered      | 2017-11-18 19:28:06        | 2017-11-18 19:45:59 | 2017-11-22 13:39:59            | 2017-12-02 00:28:42             | 2017-12-15                      |
|  4 | ad21c59c0840e6cb83a9ceb5573f8159 | 8ab97904e6daea8866dbdbc4fb7aad2c | delivered      | 2018-02-13 21:18:39        | 2018-02-13 22:20:29 | 2018-02-14 19:46:34            | 2018-02-16 18:17:02             | 2018-02-26                      |


____________________________________________________________
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: datetime64[us](4), object(1), str(3)
memory usage: 6.1+ MB
None


____________________________________________________________
Shape:

(99441, 8)


____________________________________________________________
Null values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64


____________________________________________________________
Duplicates:
0

In [13]:
print("All the values of order_status")
df_orders['order_status'].value_counts()

All the values of order_status

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [14]:
series1 = df_orders[df_orders['order_approved_at'].isnull()]['order_status'].value_counts()
series2 = df_orders[df_orders['order_delivered_carrier_date'].isnull()]['order_status'].value_counts()
series3 = df_orders[df_orders['order_delivered_customer_date'].isnull()]['order_status'].value_counts()


df = pd.DataFrame([series1, series2,series3], index=['order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date'])
print("This DataFrame shows which and how many order_status's are missing from these 3 features")
df

This DataFrame shows which and how many order_status's are missing from these 3 features

order_status,canceled,delivered,created,unavailable,invoiced,processing,approved,shipped
order_approved_at,141.0,14.0,5.0,NaN,NaN,NaN,NaN,NaN
order_delivered_carrier_date,550.0,2.0,5.0,609.0,314.0,301.0,2.0,NaN
order_delivered_customer_date,619.0,8.0,5.0,609.0,314.0,301.0,2.0,1107.0

#### 7. Products
- Many null values for - category name, name length, photos, description length
- Keep the null values as - `UNKOWN` Because we cannot remove these rows - doing so will remove many genuine product_ids which are related to different features on different tables

In [15]:
measures(df_products)

|    | product_id                       | product_category_name   |   product_name_length |   product_description_length |   product_photos_qty |   product_weight_g |   product_length_cm |   product_height_cm |   product_width_cm |
|---:|:---------------------------------|:------------------------|----------------------:|-----------------------------:|---------------------:|-------------------:|--------------------:|--------------------:|-------------------:|
|  0 | 1e9e8ef04dbcff4541ed26657ea517e5 | perfumery               |                    40 |                          287 |                    1 |                225 |                  16 |                  10 |                 14 |
|  1 | 3aa071139cb16b67ca9e5dea641aaa2f | art                     |                    44 |                          276 |                    1 |               1000 |                  30 |                  18 |                 20 |
|  2 | 96bd76ec8810374ed1b65e291975717f | sports_leisure          |                    46 |                          250 |                    1 |                154 |                  18 |                   9 |                 15 |
|  3 | cef67bcfe19066a932b7673e239eb23d | baby                    |                    27 |                          261 |                    1 |                371 |                  26 |                   4 |                 26 |
|  4 | 9dc1a7de274444849c219cff195d0b71 | housewares              |                    37 |                          402 |                    4 |                625 |                  20 |                  17 |                 13 |


____________________________________________________________
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_length         32341 non-null  float64
 3   product_description_length  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB
None


____________________________________________________________
Shape:

(32951, 9)


____________________________________________________________
Null values:
product_id                      0
product_category_name         610
product_name_length           610
product_description_length    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64


____________________________________________________________
Duplicates:
0

In [16]:
df_products[df_products['product_height_cm'].isnull()]

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8582,09ff539a621711667c43eba6a3bd8466,baby,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18852,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 8. Sellers

In [17]:
measures(df_sellers)

|    | seller_id                        |   seller_zip_code_prefix | seller_city       | seller_state   |
|---:|:---------------------------------|-------------------------:|:------------------|:---------------|
|  0 | 3442f8959a84dea7ee197c632cb2df15 |                    13023 | campinas          | SP             |
|  1 | d1b65fc7debc3361ea86b5f14c68d2e2 |                    13844 | mogi guacu        | SP             |
|  2 | ce3ad9de960102d0677a81f5d0bb7b2d |                    20031 | rio de janeiro    | RJ             |
|  3 | c0f3eea2e14555b6faeea3dd58c1b1c3 |                    04195 | sao paulo         | SP             |
|  4 | 51a04a8a6bdcb23deccc82b0b80742cf |                    12914 | braganca paulista | SP             |


____________________________________________________________
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   str
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: str(4)
memory usage: 96.8 KB
None


____________________________________________________________
Shape:

(3095, 4)


____________________________________________________________
Null values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64


____________________________________________________________
Duplicates:
0